
import {  Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import ClientWrapper from "./ClientWrapper";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],

})

export const metadata = {
  title: "Lockli",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className={`${inter.variable} `}>
        <ClientWrapper>
          <div className="nav__wrapper">
          <Nav />
        </div>
        {children}
        </ClientWrapper>
      </body>
    </html>
  );
}
